
<center>

---

# **Pandas**
---



<img src="https://drive.google.com/uc?id=1j2U9Wy535lSBdrxTCtCyseo44DWWF3gO" width="300px" height="150">
</center>

In [1]:
# Si no tiene instalado pandas
#!pip install pandas

Después de la instalación, se puede importar. La versión se puede comprobar de la siguiente manera:

In [2]:
# Importar librerias
import pandas as pd
import numpy as np

In [3]:
# Pandas Version
pd.__version__

'1.2.5'

## **pandas objects**

<img src ="https://drive.google.com/uc?id=10wU_f9PK5_nxb-mpPoT6TZLw_AO5IfxJ" width="600px" height="300px" >

# cargar una base de datos

https://drive.google.com/file/d/1JpwTmTgOvecPp8coRHZAXJoLhSEuWgiN/view?usp=sharing


https://drive.google.com/file/d/1JpwTmTgOvecPp8coRHZAXJoLhSEuWgiN/view?usp=sharing

In [4]:
import pandas as pd
import numpy as np

In [5]:
titanic=pd.read_csv("https://github.com/Wilsonsr/Programacion-en-Lenguajes-Estadisticos/raw/main/BASES/train.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Pre-procesamiento de nuestros datos

Ahora que tenemos una idea de en qué consiste nuestro conjunto de datos, vamos a transformarlo para poder visualizar la fase. Los tipos de actividades que podemos realizar durante el **preprocesamiento** incluyen

1. **Eliminar columnas**
2. **Enriquecer (o transformar)** un conjunto de datos, añadiendo nuevas columnas calculadas en los índices
3. **Filtrar** un subconjunto de filas o columnas de un conjunto de datos según algún criterio
4. **Indexar** un conjunto de datos
5. **Agregar** datos
6. **Ordenar** las filas de un conjunto de datos según algún criterio
7. **Fusionar** los datos
8. **Pivotar** de forma que los datos que originalmente estaban dispuestos en vertical se dispongan en horizontal (aumentando el número de columnas) o viceversa (aumentando el número de filas)

entre otros.

In [6]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

- Eliminar las columnas `PassengerId`, `Name` , Cabin, no vamos a eliminar la columna del billete todavía.

In [7]:
titanic.drop(['PassengerId','Name','Cabin'],axis=1, inplace=True)
titanic.shape

(891, 9)

In [8]:
# Validación nula de nuevo
titanic.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      2
dtype: int64

In [9]:
# En los primeros 10 registros tenemos un campo de edad nulo, lo vamos a tener como referencia para lo que vamos a hacer
titanic.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
5,0,3,male,NaN,0,0,330877,8.4583,Q
6,0,1,male,54.0,0,0,17463,51.8625,S
7,0,3,male,2.0,3,1,349909,21.0750,S
8,1,3,female,27.0,0,2,347742,11.1333,S
9,1,2,female,14.0,1,0,237736,30.0708,C

### **Valores nulos**

Dependiendo del problema, el tratamiento de los nulos puede ser manejado de diferentes maneras:

* Mantenerlos
* Borrarlos
* Dejar un valor fijo que los diferencie
* Sustituirlos por un estadístico de resumen (media, mediana, moda)
* Rellenar hacia delante o hacia atrás
* Interpolar

In [10]:
# Delete
titanic.dropna(inplace=True)
titanic.shape

(712, 9)

In [11]:
# Validación nulos
titanic.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [12]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  712 non-null    int64
 1   Pclass    712 non-null    int64
 2   Sex       712 non-null    object
 3   Age       712 non-null    float64
 4   SibSp     712 non-null    int64
 5   Parch     712 non-null    int64
 6   Ticket    712 non-null    object
 7   Fare      712 non-null    float64
 8   Embarked  712 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 55.6+ KB

In [13]:
titanic.reset_index(drop=True,inplace=True)
titanic.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
5,0,1,male,54.0,0,0,17463,51.8625,S
6,0,3,male,2.0,3,1,349909,21.0750,S
7,1,3,female,27.0,0,2,347742,11.1333,S
8,1,2,female,14.0,1,0,237736,30.0708,C
9,1,3,female,4.0,1,1,PP 9549,16.7000,S

In [14]:
# Deja un valor fijo que los diferencie
titanic = pd.read_csv("https://drive.google.com/uc?id=1_uYmhihRAPXkYky1G_cJri5IV0-szgjP")
titanic.drop(['PassengerId','Name','Cabin'],axis=1, inplace=True)

In [15]:
titanic.shape

(891, 9)

In [16]:
titanic.fillna(-1).head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
5,0,3,male,-1.0,0,0,330877,8.4583,Q
6,0,1,male,54.0,0,0,17463,51.8625,S
7,0,3,male,2.0,3,1,349909,21.0750,S
8,1,3,female,27.0,0,2,347742,11.1333,S
9,1,2,female,14.0,1,0,237736,30.0708,C

In [17]:
titanic.fillna(titanic['Age'].mean()).head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.000000,1,0,A/5 21171,7.2500,S
1,1,1,female,38.000000,1,0,PC 17599,71.2833,C
2,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.000000,1,0,113803,53.1000,S
4,0,3,male,35.000000,0,0,373450,8.0500,S
5,0,3,male,29.699118,0,0,330877,8.4583,Q
6,0,1,male,54.000000,0,0,17463,51.8625,S
7,0,3,male,2.000000,3,1,349909,21.0750,S
8,1,3,female,27.000000,0,2,347742,11.1333,S
9,1,2,female,14.000000,1,0,237736,30.0708,C

In [18]:
titanic['Age'].fillna(titanic['Age'].median()).head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    28.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [19]:
titanic['Age'].fillna(titanic['Age'].mode()[0]).head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    24.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [20]:
titanic['Age'].fillna(method='backfill').head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    54.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [21]:
titanic['Age'].fillna(method='ffill').head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    35.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [22]:
titanic.interpolate(method='polynomial', order=2).head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.000000,1,0,A/5 21171,7.2500,S
1,1,1,female,38.000000,1,0,PC 17599,71.2833,C
2,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.000000,1,0,113803,53.1000,S
4,0,3,male,35.000000,0,0,373450,8.0500,S
5,0,3,male,56.320363,0,0,330877,8.4583,Q
6,0,1,male,54.000000,0,0,17463,51.8625,S
7,0,3,male,2.000000,3,1,349909,21.0750,S
8,1,3,female,27.000000,0,2,347742,11.1333,S
9,1,2,female,14.000000,1,0,237736,30.0708,C

Para nuestro ejercicio tomaremos la decisión de eliminar los nulos.

---

In [23]:
# Drop nulls
titanic.dropna(inplace=True)
titanic.shape

(712, 9)

In [24]:
titanic.reset_index(drop=True , inplace=True)
titanic.head(7)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
5,0,1,male,54.0,0,0,17463,51.8625,S
6,0,3,male,2.0,3,1,349909,21.0750,S

### Cambio de nombre de las columnas

Para ser prácticos, normalmente modificamos los nombres de las columnas para eliminar los espacios en blanco y los caracteres especiales, y para convertir las mayúsculas en minúsculas:

-  Cambiar el nombre de las columnas a minúsculas

In [25]:
titanic.rename(columns = lambda col: col.lower(),inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,ticket,fare,embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...
707,0,3,female,39.0,0,5,382652,29.1250,Q
708,0,2,male,27.0,0,0,211536,13.0000,S
709,1,1,female,19.0,0,0,112053,30.0000,S
710,1,1,male,26.0,0,0,111369,30.0000,C
711,0,3,male,32.0,0,0,370376,7.7500,Q

**Sintaxis de una función Lambda**

`lambda argumentos: expresión`

Las funciones Lambda pueden tener cualquier número de argumentos, pero solo una expresión.

In [26]:
# Validando dataset
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  712 non-null    int64
 1   pclass    712 non-null    int64
 2   sex       712 non-null    object
 3   age       712 non-null    float64
 4   sibsp     712 non-null    int64
 5   parch     712 non-null    int64
 6   ticket    712 non-null    object
 7   fare      712 non-null    float64
 8   embarked  712 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 50.2+ KB

In [27]:
titanic.shape

(712, 9)

### Indexación

In [28]:
# Después de eliminar los nulos, hay que reiniciar los índices, como puedes ver siguen apareciendo de 0 a 890 
# aunque tengamos 712 filas.
titanic.reset_index(drop=True,inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,ticket,fare,embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...
707,0,3,female,39.0,0,5,382652,29.1250,Q
708,0,2,male,27.0,0,0,211536,13.0000,S
709,1,1,female,19.0,0,0,112053,30.0000,S
710,1,1,male,26.0,0,0,111369,30.0000,C
711,0,3,male,32.0,0,0,370376,7.7500,Q

### **Agrupación**

<img src="https://drive.google.com/uc?id=1h4sbR-AXgzcdZ2eCtBpQiDGPfcF8Q-gL" width="400px" heigt="400px">

In [29]:
titanic.groupby(['sex','survived']).size()

sex     survived
female  0            64
        1           195
male    0           360
        1            93
dtype: int64

In [30]:
titanic.groupby(['sex','survived']).agg({'fare':'count','age':'mean'}).reset_index()

      sex  survived  fare        age
0  female         0    64  25.046875
1  female         1   195  28.630769
2    male         0   360  31.618056
3    male         1    93  27.276022

In [31]:
# Validar los tickets duplicados
df_tickets = titanic.groupby('ticket').size().reset_index().rename(columns={0:'count'})
df_tickets
df_tickets.sort_values(by='count',ascending=False)

           ticket  count
273        347082      7
445       CA 2144      6
207       3101295      6
277        347088      6
490  S.O.C. 14879      5
..            ...    ...
242        345763      1
241        345572      1
240        345364      1
239        343276      1
270        347078      1

[541 rows x 2 columns]

In [32]:
titanic[titanic['ticket']=='347082']

     survived  pclass     sex   age  sibsp  parch  ticket    fare embarked
12          0       3    male  39.0      1      5  347082  31.275        S
93          0       3  female   2.0      4      2  347082  31.275        S
428         0       3  female   9.0      4      2  347082  31.275        S
429         0       3  female  11.0      4      2  347082  31.275        S
481         0       3  female  39.0      1      5  347082  31.275        S
649         0       3  female   6.0      4      2  347082  31.275        S
676         0       3    male   4.0      4      2  347082  31.275        S

In [33]:
titanic[titanic['ticket']=='110413']

     survived  pclass     sex   age  sibsp  parch  ticket   fare embarked
210         0       1    male  52.0      1      1  110413  79.65        S
442         1       1  female  39.0      1      1  110413  79.65        S
462         1       1  female  18.0      0      2  110413  79.65        S

### Ordering

In [34]:
# Ordenar el número de registros por entradas
df_tickets.sort_values(by=["count"],ascending=False,inplace=True)
df_tickets.head(10)

           ticket  count
273        347082      7
445       CA 2144      6
207       3101295      6
277        347088      6
490  S.O.C. 14879      5
376        382652      5
77          19950      4
65           1601      4
28         113781      4
451          LINE      4

In [35]:
# Vamos a validar un ticket
titanic[titanic['ticket']=='347082']

     survived  pclass     sex   age  sibsp  parch  ticket    fare embarked
12          0       3    male  39.0      1      5  347082  31.275        S
93          0       3  female   2.0      4      2  347082  31.275        S
428         0       3  female   9.0      4      2  347082  31.275        S
429         0       3  female  11.0      4      2  347082  31.275        S
481         0       3  female  39.0      1      5  347082  31.275        S
649         0       3  female   6.0      4      2  347082  31.275        S
676         0       3    male   4.0      4      2  347082  31.275        S

### Merging datasets

In [36]:
# Primero añadiremos la columna 'count' de df_tickets a nuestro conjunto de datos titanic
titanic = titanic.merge(df_tickets,left_on='ticket',right_on='ticket',how='left')
titanic.shape

(712, 10)

In [37]:
titanic.head(15)

,survived,pclass,sex,age,sibsp,parch,ticket,fare,embarked,count
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S,1
1,1,1,female,38.0,1,0,PC 17599,71.2833,C,1
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,1
3,1,1,female,35.0,1,0,113803,53.1000,S,2
4,0,3,male,35.0,0,0,373450,8.0500,S,1
5,0,1,male,54.0,0,0,17463,51.8625,S,1
6,0,3,male,2.0,3,1,349909,21.0750,S,4
7,1,3,female,27.0,0,2,347742,11.1333,S,3
8,1,2,female,14.0,1,0,237736,30.0708,C,2
9,1,3,female,4.0,1,1,PP 9549,16.7000,S,2
10,1,1,female,58.0,0,0,113783,26.5500,S,1
11,0,3,male,20.0,0,0,A/5. 2151,8.0500,S,1
12,0,3,male,39.0,1,5,347082,31.2750,S,7
13,0,3,female,14.0,0,0,350406,7.8542,S,1
14,1,2,female,55.0,0,0,248706,16.0000,S,1

In [38]:
df_A = pd.DataFrame({
    'Fecha': ['24/06/2021', '25/06/2021', '26/06/2021'],
    'Datos_A': [1, 5, 9]
})

In [39]:
df_A

        Fecha  Datos_A
0  24/06/2021        1
1  25/06/2021        5
2  26/06/2021        9

In [40]:
df_B = pd.DataFrame({
    'Fecha': ['24/06/2021', '25/06/2021', '26/06/2021', '27/06/2021'],
    'Datos_B': [7, 5, 3, 4]
})

In [41]:
df_B

        Fecha  Datos_B
0  24/06/2021        7
1  25/06/2021        5
2  26/06/2021        3
3  27/06/2021        4

In [42]:
df_A.Fecha = pd.to_datetime(df_A.Fecha)
df_B.Fecha = pd.to_datetime(df_B.Fecha)

In [43]:
df = pd.merge(df_A, df_B, on='Fecha', how='outer')
df
#df.sort_values(by='Fecha', inplace=True)
#df[['Fecha', 'Datos_A', 'Datos_B']]

       Fecha  Datos_A  Datos_B
0 2021-06-24      1.0        7
1 2021-06-25      5.0        5
2 2021-06-26      9.0        3
3 2021-06-27      NaN        4

## **Melt**

La función `pd.melt()` remodela o transforma un DataFrame existente. Cambia la orientación del DataFrame de un formato ancho a uno largo.

<img src="https://drive.google.com/uc?id=19gZqC45_VptAmtGp9zZLSri2rhq85vDm" width="500px" height=" 300px" >

In [44]:
dataframe=pd.DataFrame({'Asistencia': {0: 60, 1: 100, 2: 80,3: 78,4: 95},
                    'Nombre': {0: 'Andres', 1: 'John', 2: 'Laura',3: 'Wilson',4: 'Jorge'},
                    'porcentaje obtenido': {0: '90%', 1: '75%', 2: '82%',3: '64%',4: '45%'}})
dataframe

   Asistencia  Nombre porcentaje obtenido
0          60  Andres                 90%
1         100    John                 75%
2          80   Laura                 82%
3          78  Wilson                 64%
4          95   Jorge                 45%

In [45]:
dataframe1 = pd.melt(dataframe)
dataframe1

               variable   value
0            Asistencia      60
1            Asistencia     100
2            Asistencia      80
3            Asistencia      78
4            Asistencia      95
5                Nombre  Andres
6                Nombre    John
7                Nombre   Laura
8                Nombre  Wilson
9                Nombre   Jorge
10  porcentaje obtenido     90%
11  porcentaje obtenido     75%
12  porcentaje obtenido     82%
13  porcentaje obtenido     64%
14  porcentaje obtenido     45%

In [46]:
dataframe2 = pd.melt(dataframe,  id_vars=['Nombre'])
dataframe2

   Nombre             variable value
0  Andres           Asistencia    60
1    John           Asistencia   100
2   Laura           Asistencia    80
3  Wilson           Asistencia    78
4   Jorge           Asistencia    95
5  Andres  porcentaje obtenido   90%
6    John  porcentaje obtenido   75%
7   Laura  porcentaje obtenido   82%
8  Wilson  porcentaje obtenido   64%
9   Jorge  porcentaje obtenido   45%

In [47]:
dataframe3 = pd.melt(dataframe, 
                     id_vars=['Nombre'], 
                     var_name = 'Performance', 
                     value_name = 'Success')
dataframe3

   Nombre          Performance Success
0  Andres           Asistencia      60
1    John           Asistencia     100
2   Laura           Asistencia      80
3  Wilson           Asistencia      78
4   Jorge           Asistencia      95
5  Andres  porcentaje obtenido     90%
6    John  porcentaje obtenido     75%
7   Laura  porcentaje obtenido     82%
8  Wilson  porcentaje obtenido     64%
9   Jorge  porcentaje obtenido     45%

In [48]:
dataframe4 = pd.melt(dataframe, id_vars=['Nombre'], value_vars='Attendance', var_name = 'Performance', value_name = 'Success')
dataframe4

   Nombre          Performance Success
0  Andres  porcentaje obtenido     90%
1    John  porcentaje obtenido     75%
2   Laura  porcentaje obtenido     82%
3  Wilson  porcentaje obtenido     64%
4   Jorge  porcentaje obtenido     45%

In [49]:
print(dataframe3.pivot(index='Nombre', columns='Performance', values='Success'))

Performance Asistencia porcentaje obtenido
Nombre
Andres              60                 90%
John               100                 75%
Jorge               95                 45%
Laura               80                 82%
Wilson              78                 64%

R en python

In [50]:
%load_ext rpy2.ipython

ModuleNotFoundError: No module named 'rpy2'

In [0]:
%%R

x=c(4,5,7)
mean(x)
var(x)
y=c(3,6,8)
x+y

### Enriquecer el conjunto de datos

Vamos a **enriquecer** este conjunto de datos creando una nueva columna `familia`, que será "1" si el viaje se realizó con otras personas, y "0" si viajaron solos:

In [0]:
titanic['family'] = [1 if count>1 else 0 for count in titanic['count']]

In [0]:
titanic.head()

### Cleaning text

In [0]:
# vamos a crear una función que nos ayude a limpiar el texto, en este caso el campo tickets
def clean_text(string):
    import re
    regex = '[^A-Za-z0-9]+'
    return re.sub(regex, '', string)

In [0]:
titanic['ticket'] = titanic['ticket'].apply(clean_text)
titanic.head()

In [0]:
# Para continuar borrar la columna ticket
titanic.drop('ticket',axis=1,inplace=True)
titanic.head()

### Codificación de variables categóricas

A veces, es útil crear una columna para cada categoría posible de una de nuestras variables categóricas. Para ello, utilizamos un método `pandas` llamado `get_dummies()`:

In [0]:
titanic['sexDummies'] = titanic['sex']
titanic = pd.get_dummies(titanic, columns = ['sexDummies'], prefix = ['D'])
titanic.head()

In [0]:
# Su código...

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f9fb0295-32a5-45e6-9900-a1209e9efec3' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>